package com.day8.Exceptionhandling;

public class NestedTry {
	public static void main(String args[]) {
		try {
			
	   int[] array1= {1,2};		
		int array1Length = array1.length;
		/* 	the following statement will generate a divide-by-zero exception. */
		int number = 42 / array1Length;
		System.out.println("array length = " + array1Length);
		try { // nested try block
		/* If one command-line arg is used,
		then a divide-by-zero exception
		will be generated by the following code. */
		if(array1Length==1) 
			array1Length = array1Length/(array1Length-array1Length);  // division by zero
		
		/* If array length is 2,	then generate an out-of-bounds exception. */
		if(array1Length==2) {
		int array2[] = { 1 };   
		array2[42] = 99; // generate an out-of-bounds exception
	    	}
	
	
		} 
		
		
		catch(ArrayIndexOutOfBoundsException e) 
		{
		System.out.println("Array index out-of-bounds: " + e);
		}
		} 
		
		catch(ArithmeticException e)
		{
		System.out.println("Divide by 0: " + e);
		}
		}
}
